[package]
name = "trading-volumn-request"
version = "0.1.0"
edition = "2021"

[dependencies]
coprocessor-sdk = { workspace = true }
trading-volumn-lib ={ path = "../lib" }
serde.workspace = true
serde_json.workspace = true
log = "0.4.14"
env_logger = "0.10.0"